'''
Controls all plotting of EofScd:
    Functions: 
        --> bin_data: 
        --> merga_data:
        --> read_datafile:
        --> temperature_avg:
        --> R plot specific functions
        
1. read_datafile('name', 'file.dat')
2. bin_data('name', 'interactions_pair(e.g. w_w)')
'''
import os, sys
import re
import numpy as np
import rpy2.robjects.lib.ggplot2 as ggplot2
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects.lib.ggplot2 import ggplot
base = importr('base')
datatable = importr('data.table')
gr = importr('grDevices')

#possible_interaction = {'complete': 'w_W',\
#                        'headtail':''}



carbonlist = []
for i in range(7):
    for j in range(7):
        if j > i:
            continue
        else:
            carbonlist.append('C{0}_C{1}'.format(i,j))

carbonlist = ['C0_C0', 'C1_C1', 'C2_C2', 'C3_C3', 'C4_C4', 'C5_C5', 'C6_C6']

Tranges = {\
           'dppc':[290, 360],\
           'dppc_chol':[290, 350],\
           'dppc_dupc':[320, 330,],\
           'dppc_dupc_chol':[290, 330],\
           'dppc_dupc_chol05':[290, 330],\
           'dppc_dupc_chol40':[290, 330],\
#           'dupc_chol':[270, 330],\
           }
#===============================================================================
# interactions = {\
#                 'complete':['w_w'],\
#                 'head-tail': ['h_h', 'h_t', 't_t',],\
# #                'head-tailhalfs':['h_h', 'h_t12', 'h_t22', 'h_w',\
# #                                    't12_t12', 't12_t22', 't12_w',\
# #                                    't22_t22', 't22_w',\
# #                                    'w_w'],\
#                 'head-tailhalfs':[\
#                                     't12_t12', 't12_t22', 't12_w',\
#                                     't22_t22', 't22_w',\
#                                     'w_w'],\
#                 'carbons':carbonlist,\
#                 }
#===============================================================================


def p_of_N(datafilename, lipidtype, outputfilename, count_type='Ntot'):
    ''' '''
    df = read_datafile('df', datafilename)
    print(df)
    aes = ggplot2.aes_string(x='Ntot', fill='factor(Scd)', y=lipidtype)
    plot = ggplot2.ggplot(df)\
            + aes\
            + ggplot2.ggtitle(lipidtype)\
            + ggplot2.geom_bar(stat="identity", position="dodge")\
            + ggplot2.theme_light() + my_theme()\
            + ggplot2.scale_y_continuous('Frequency')\
            + add_axis('x', 'Number of '+count_type, breaks=[0, 10, 1])
    gr.pdf(file=outputfilename, width=10, height=6)
    print(plot)
    gr.dev_off()
#            + add_axis('y', 'Frequency', breaks=[0.0, 25000, 2000])


def my_rdfplots(system, temperature, particlespair):
    ''' Plots data generated by selfimplementation of radial distribution function '''
    ncholranges = {'dppc_chol':3,
                   'dppc_dupc_chol':3,
                   'dppc_dupc_chol05':2,
                   'dppc_dupc_chol40':5,
                    }
    temp = temperature
    #if ncholrange is not None:
    outputfile_name = 'rdf_{0}_{1}_{2}.pdf'.format(system, temp, particlespair)
    #frame_regex = re.compile(r'(.*)(\..*)$')
    datafile_name = '{0}_{1}/rdf_{2}.dat'\
                        .format(system, temp, particlespair)
    dataframes = {}
    dataframes['complete'] = ro.r('dtcomplete <- fread("{0}")'.format(datafile_name)
                                  )
    framespecifiers = [['dtcomplete', 'complete']]
    for nchol in range(ncholranges[system]+1):
        datafile_name = '{0}_{1}/rdf_{2}_{3}.dat'\
                            .format(system, temp, particlespair, nchol)
        dataframes[nchol] = ro.r('dt{0} <- fread("{1}")'.format(nchol, datafile_name))
        framespecifiers.append(['dt'+str(nchol), nchol])
    dt = merge_data('dt', 'NChol', *framespecifiers)
    aes = ggplot2.aes_string(x='V1', y='V2', color='NChol')
    plot = ggplot2.ggplot(dt)\
            + aes\
            + ggplot2.geom_point(alpha='0.6')\
            + ggplot2.geom_line()\
            + ggplot2.theme_light() + my_theme()
            #===================================================================
            # + add_axis('x', 'distance r / nm', breaks=[0.0, 1.5, 0.2])\
            # + add_axis('y', 'g(r)', breaks=[0.0, 1.1, 0.2])\
            #===================================================================
#            + ggplot2.geom_smooth(se='False', span='0.01', n=900)\
    if isinstance(temperature, list):
        plot += ggplot2.facet_grid('Temperature ~ .')
    gr.pdf(file=outputfile_name, width=10, height=6)
    print(plot)
    #save_plot(outputfile_name, plot, width=25, height=15)
    gr.dev_off()



#def rdfplot(datafile, outputfile_name, ncholrange=None, temperature=None):
def rdfplot(system, temperature, interaction, lipid=None, ncholrange=None):
    ''' creates an rdf-plot
        datafilename path: <system>_<temperature>/datafiles/rdf/rdf_<inter1>_<inter2>.xvg
        system:         systemname
        temperature:    can be either a list with [Tstart, Tend] or an integer
        interaction:    tuple ('HEAD', 'HEAD') or ('HEAD', 'TAIL')
        ncholrange:     range for datafiles with nchol specification can be given with [start, end, step]
        allsys:         list of systems
    '''
    print("inputparameters:", system, temperature, interaction, lipid, ncholrange)
    if isinstance(temperature, list):
        tempframes = []
        for temp in range(temperature[0], temperature[1]+1, temperature[2]):
            if ncholrange is not None:
                outputfile_name = 'rdf_{0}_tavg_{2}_{3}{4}_nchol.pdf'.format(system, temp, lipid, *interaction)
                #frame_regex = re.compile(r'(.*)(\..*)$')
                dataframes = {}
                framespecifiers = []
                for nchol in range(ncholrange[0], ncholrange[1]+1):
                    datafile_name = '{0}_{1}/datafiles/rdf/rdf_{3}-{2}-{4}-{2}{5}.xvg'\
                                    .format(system, temp, lipid, interaction[0], interaction[1], nchol)
                    #regmatch = re.match(frame_regex, datafile)
                    #filesuffix = regmatch.group(2)
                    #dtfile_name = regmatch.group(1)+str(nchol)+filesuffix
                    dataframes[(temp, nchol)] = ro.r(\
                                                     'dt{2}{0} <- fread("{1}")'
                                                     '\ndt{2}{0}<-dt{2}{0}[V1>0.1]'
                                                     '\ndt{2}{0}$V2 <- dt{2}{0}$V2/max(dt{2}{0}$V2)'
                                                     '\ndt{2}{0}$temp <- {2}'
                                                     '\ndt{2}{0}'.format(nchol, datafile_name, temp))
                    print("dataframe:", dataframes[(temp, nchol)])
                    framespecifiers.append(['dt'+str(temp)+str(nchol), nchol])
                dt = merge_data('dt'+str(temp), 'NChol', *framespecifiers)
                tempframes.append(['dt'+str(temp), temp])
                aes = ggplot2.aes_string(x='V1', y='V2', color='NChol')
            elif isinstance(system, list):
                outputfile_name = 'rdf_all_tavg_{1}_{2}{3}.pdf'.format(temp, lipid, *interaction)
                #frame_regex = re.compile(r'(.*)(\..*)$')
                dataframes = {}
                framespecifiers = []
                for syst in system:
                    datafile_name = '{0}_{1}/datafiles/rdf/rdf_{3}-{2}-{4}-{2}None.xvg'\
                                    .format(syst, temp, lipid, interaction[0], interaction[1])
                    #regmatch = re.match(frame_regex, datafile)
                    #filesuffix = regmatch.group(2)
                    #dtfile_name = regmatch.group(1)+str(nchol)+filesuffix
                    dataframes[(temp, syst)] = ro.r(\
                                                     'dt{2}{0} <- fread("{1}")'
                                                     '\ndt{2}{0}<-dt{2}{0}[V1>0.1]'
                                                     '\ndt{2}{0}$V2 <- dt{2}{0}$V2/max(dt{2}{0}$V2)'
                                                     '\ndt{2}{0}$temp <- {2}'
                                                     '\ndt{2}{0}'.format(syst, datafile_name, temp))
                    print("dataframe:", dataframes[(temp, syst)])
                    framespecifiers.append(['dt'+str(temp)+str(syst), syst])
                dt = merge_data('dt'+str(system)+str(temp), 'System', *framespecifiers)
                print("THIS IS DT at", temp, "\n", dt)
                tempframes.append(['dt'+str(system)+str(temp), temp])
                aes = ggplot2.aes_string(x='V1', y='V2', color='System')
            else:
                if lipid is None:
                    lipid = ''
                outputfile_name = 'rdf_{0}_tavg_{2}_{3}{4}.pdf'.format(system, temp, lipid, *interaction)
                datafile_name = '{0}_{1}/datafiles/rdf/rdf_{2}-{3}.xvg'\
                                    .format(system, temp, interaction[0], interaction[1])
                dataframes = {}
                dataframes[temp] = ro.r('dt{0} <- fread("{1}")'
                                        #'\ndt{0}$V2 <- dt{0}$V2/max(dt{0}$V2)'
                                        '\ndt{0}$temp <- {2}'.format(temp, datafile_name, temp))
                tempframes.append(['dt'+str(temp), temp])
                aes = ggplot2.aes_string(x='V1', y='V2')
        dt = merge_data('dt_tavg', 'Temperature', *tempframes)
        print(dt)
    else:
        temp = temperature
        if ncholrange is not None:
            outputfile_name = 'rdf_{0}_{1}_{2}_{3}{4}_nchol.pdf'.format(system, temp, lipid, *interaction)
            #frame_regex = re.compile(r'(.*)(\..*)$')
            dataframes = {}
            framespecifiers = []
            for nchol in range(ncholrange[0], ncholrange[1]+1):
                datafile_name = '{0}_{1}/datafiles/rdf/rdf_{3}-{2}-{4}-{2}{5}.xvg'\
                                    .format(system, temp, lipid, interaction[0], interaction[1], nchol)
                #regmatch = re.match(frame_regex, datafile)        
                #filesuffix = regmatch.group(2)
                #dtfile_name = regmatch.group(1)+str(nchol)+filesuffix
                dataframes[nchol] = ro.r('dt{0} <- fread("{1}")'
                                          '\ndt{0}<-dt{0}[V1>0.1]'
                                          #'\ndt{0}$V2 <- dt{0}$V2/max(dt{0}$V2)'
                                          '\ndt{0}'.format(nchol, datafile_name))
                framespecifiers.append(['dt'+str(nchol), nchol])
            dt = merge_data('dt', 'NChol', *framespecifiers)
            aes = ggplot2.aes_string(x='V1', y='V2', color='NChol')
        else:
            datafile_name = '{0}_{1}/datafiles/rdf/rdf_{3}-{2}-{4}-{2}None.xvg'\
                                .format(system, temp, lipid, interaction[0], interaction[1])
            outputfile_name = 'rdf_{0}_{1}_{2}_{3}{4}.pdf'.format(system, temp, lipid, *interaction)
            dt = ro.r('{0} <- fread("{1}")'
                          '\n{0}<-{0}[V1>0.1]'
                          #'\n{0}$V2 <- {0}$V2/max({0}$V2)'
                          '\n{0}'.format('dt_raw', datafile_name))
            aes = ggplot2.aes_string(x='V1', y='V2')
    plot = ggplot2.ggplot(dt)\
            + aes\
            + ggplot2.geom_point(alpha='0.6')\
            + add_axis('x', 'distance r / nm', breaks=[0.0, 1.5, 0.2])\
            + ggplot2.scale_y_continuous(name='g(r)')\
            + ggplot2.theme_light() + my_theme()\
#            + ggplot2.geom_smooth(se='False', span='0.01', n=900)\
    if isinstance(temperature, list):
        plot += ggplot2.facet_grid('Temperature ~ .')
    gr.pdf(file=outputfile_name, width=10, height=6)
    print(plot)
    #save_plot(outputfile_name, plot, width=25, height=15)
    gr.dev_off()

def Nrplot(system, temperature, interaction):
    ''' '''
    if isinstance(temperature, list):
        tempframes = []
        for temp in range(temperature[0], temperature[1]+1, temperature[2]):
            outputfile_name = 'nr_{0}_{2}{3}.pdf'.format(system, temp, *interaction)
            datafile_name = '{0}_{1}/datafiles/rdf/nr_{2}-{3}.xvg'\
                                .format(system, temp, interaction[0], interaction[1])
            dataframes = {}
            dataframes[temp] = ro.r('dt{0} <- fread("{1}")'
                  '\ndt{0}$temp <- {2}'.format(temp, datafile_name, temp))
            tempframes.append(['dt'+str(temp), temp])
        aes = ggplot2.aes_string(x='V1', y='V2')
        dt = merge_data('dt_tavg', 'Temperature', *tempframes)
    else:
        datafile_name = '{0}_{1}/datafiles/rdf/nr_{2}-{3}.xvg'\
                                .format(system, temp, interaction[0], interaction[1])
        outputfile_name = 'nr_{0}_{1}_{2}_{3}.pdf'.format(system, temp, *interaction)
        dt = ro.r('{0} <- fread("{1}")'
                      '\n{0}<-{0}[V1>0.1]'
                      '\n{0}'.format('dt_raw', datafile_name))
        aes = ggplot2.aes_string(x='V1', y='V2')
    if interaction == ('P', 'P'):
        ybreaks = [0.0, 6.5, 1.5]
        yline = 4
    else:
        ybreaks = [0.0, 1.4, 0.3]
        yline  = 1
    plot = ggplot2.ggplot(dt)\
        + aes\
        + ggplot2.geom_point(alpha='0.6')\
        + ggplot2.geom_hline(yintercept=yline)\
        + add_axis('x', 'distance r / nm', breaks=[0.4, 1.2, 0.2])\
        + add_axis('y', "N(r)", breaks=ybreaks)\
        + ggplot2.ggtitle("{}-{}".format(*interaction))\
        + ggplot2.theme_light() + my_theme()\
#            + ggplot2.geom_smooth(se='False', span='0.01', n=900)\
    if isinstance(temperature, list):
        plot += ggplot2.facet_grid('Temperature ~ .')
    gr.pdf(file=outputfile_name, width=10, height=6)
    print(plot)
    #save_plot(outputfile_name, plot, width=25, height=15)
    gr.dev_off()

class NofScdplots():
    ''' '''
    def __init__(self, systemnames=Tranges.keys()):
        self.lipidranges = {'DPPC':(3, 6, 1), 'CHL1':(2, 5, 0.5), 'DUPC':(3, 8, 1)}
        #self.enthalpyranges = {}
        self.systemnames = systemnames
        self.Tlow = {}
        self.Thigh = {}
        for syst in systemnames:
            self.Tlow[syst], self.Thigh[syst] = Tranges[syst]


    def plot_standard(self, systemname, lipid, filename, y_type='Ntot', neib_spec=None):
        tavg = self.temperature_avg(systemname, systemname, lipid, neib_spec)
        print(tavg)
        if lipid =='CHL1':
            lipid = 'Chol'
        if y_type != 'Ntot':
            yname = 'Number of {} neighbors of {}'.format(y_type, lipid)
        else:
            if isinstance(lipid, list):
                yname = 'Total number of neighbors'
            else:
                yname = 'Total number of neighbors'.format()
        if tavg is None:
            return
        if isinstance(neib_spec, list):
            aes =  ggplot2.aes_string(x='Host_Scd', y=y_type, )
            guide =  ggplot2.guides(color=ggplot2.guide_legend(neib_spec), shape=ggplot2.guide_legend("Lipid"))
        elif neib_spec is not None: 
            aes =  ggplot2.aes_string(x='Host_Scd', y=y_type, color='factor('+neib_spec+')')
            guide =  ggplot2.guides(color=ggplot2.guide_legend('N'+neib_spec))
        elif isinstance(lipid, list) and neib_spec is None:
            neib_spec = ''
            aes =  ggplot2.aes_string(x='Host_Scd', y=y_type, color='Lipid_type')
            guide =  ggplot2.guides(color=ggplot2.guide_legend("Lipid"))
        elif isinstance(lipid, list) and neib_spec is not None:
            neib_spec = ''
            aes =  ggplot2.aes_string(x='Host_Scd', y=y_type, shape='Lipid_type', color='factor('+neib_spec+')')
            guide =  ggplot2.guides(color=ggplot2.guide_legend(neib_spec), shape=ggplot2.guide_legend("Lipid"))
        else:
            neib_spec = ''
            aes =  ggplot2.aes_string(x='Host_Scd', y=y_type)
            guide = ggplot2.guides(shape=ggplot2.guide_legend("Dummy"))
        #dupcfunc = ggplot2.stat_function(ggplot2.aes_string(linetype='"DLiPC"'), fun=ro.r("function(x){3.52807504+0.12268938*x-0.09141714*x**2}"), color='black', size=2)
        #dppcfunc = ggplot2.stat_function(ggplot2.aes_string(linetype='"DPPC"'), fun=ro.r("function(x){(0.94123979/(1 + exp(-18.29302015 * (x - 0.63623191))) + 3.88006658)}"), color='black', size=2, )
        plot = ggplot2.ggplot(tavg)\
            + aes\
            + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
            + add_axis('x', 'scd', breaks=[-0.3, 1.0, 0.2])\
            + ggplot2.scale_y_continuous(name=yname)\
            + ggplot2.guides(color=ggplot2.guide_legend(neib_spec))\
            + ggplot2.scale_size()\
            + guide\
            + ggplot2.theme_light() + my_theme()
        gr.pdf(file=filename, width=10, height=7)
        print(plot)
        gr.dev_off()
 
    def temperature_avg(self, outputtable, systemname, lipid, neib_spec=None):
        ''' ___ Calculate average over temperature range ___
        Variables are:
            mysys: Systemname (like dppc_chol)
            Tlow['sys'], Thigh['sys']: Temperature range
            pair: lipidtype pair (DPPC_DPPC)
            interaction: part of interaction (complete/headtail/headtailhalfs/...)
            interaction_pair: (w_w/h_t/...)
            nchol: None | not None
        Final data.frame structure:
            "binAvgScd Time Host Host_Scd Neib Neib_Scd DeltaScd AvgScd Etot Evdw Ecoul NChol weight"
        '''
        print("INPUT:", outputtable, systemname, lipid)
        framenames = []
        for temp in range(self.Tlow[systemname], self.Thigh[systemname]+1, 10):
            print("At temperature:", temp)
            system = '{}_{}'.format(systemname, temp)
            print(system)
            file_to_read = '{}/Nofscd.dat'.format(system)
            if os.path.exists(file_to_read):
                df = read_datafile(system, file_to_read)
                print(df)
            else:
                print("File {} does not exist".format(file_to_read))
                return None
            #Averaging before everything's collected=============
            df = self.bin_raw_data(system, system, neib_spec=neib_spec)
            print("binned df:", df)
            framenames.append(system)
        framenames = [(i, i[-3:]) for i in framenames]
        print("Framenames:", framenames)
        dt = merge_data(outputtable, 'temperature', *framenames)
        print("MERGED DATA:", dt)
        if isinstance(lipid, list):
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))\n'
                         '{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(Lipid_type, binHost_Scd)]'\
                         .format(outputtable))
        elif isinstance(neib_spec, list):
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))\n'
                            '{0} <- {0}[Lipid_type=="{1}"]\n'
                            'insignificant <- 0.01*max({0}$weight)\n'
                            '{0} <- {0}[,Lipid_type:=NULL][weight>insignificant]\n'
                            '{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binHost_Scd, {2})]'\
                            .format(outputtable, lipid, ','.join(neib_spec)))
        else:
            if neib_spec is None:
                df_final = ro.r('{0} <- subset({0},select=-c(temperature))\n'
                                '{0} <- {0}[Lipid_type=="{1}"][Chol<4]\n'
                                '{0} <- {0}[,Lipid_type:=NULL]\n'
                             '{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=binHost_Scd]'\
                             .format(outputtable, lipid))
            else:
                df_final = ro.r('{0} <- subset({0},select=-c(temperature))\n'
                                '{0} <- {0}[Lipid_type=="{1}"]\n'
                                'insignificant <- 0.01*max({0}$weight)\n'
                                #'{0} <- {0}[,Lipid_type:=NULL][weight>insignificant]\n'
                                '{0} <- {0}[weight>insignificant]\n'
                             #'{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binHost_Scd, {2})]'\
                             '{0} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else weighted.mean(x)),by=list(binHost_Scd, {2})]'\
                             .format(outputtable, lipid, neib_spec))
        print("FINALFRAME:", df_final)
        return df_final
    def bin_raw_data(self, outputtablename, datatablename, column='Host_Scd', neib_spec=None, breakl=-0.5, breakh=1.0, breakdx=0.05):
        ''' Discretize data by aggregating specified column '''
        print("Binning... {} :".format(datatablename))
        labelbreakh = breakh-breakdx
        if neib_spec is None:
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\nbckp_data <- {0}'
                '\n{6} <- {0}[,lapply(.SD, mean), by=list(bin{1}, Lipid_type)]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Lipid_type)][,N]'
                '\n{6}'\
                .format(datatablename, column,
                        breakl, breakh, breakdx, labelbreakh,
                        outputtablename),)
        elif isinstance(neib_spec, list):
            print("Got here")
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\nbckp_data <- {0}'
                '\n{6} <- {0}[,lapply(.SD, mean), by=list(bin{1}, Lipid_type, {7})]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Lipid_type, {7})][,N]'
                '\n{6}'\
                .format(datatablename, column,
                        breakl, breakh, breakdx, labelbreakh,
                        outputtablename, ','.join(neib_spec)),)
        else:
            print("Got here")
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\nbckp_data <- {0}'
                '\n{6} <- {0}[,lapply(.SD, mean), by=list(bin{1}, Lipid_type, {7})]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Lipid_type, {7})][,N]'
                '\n{6}'\
                .format(datatablename, column,
                        breakl, breakh, breakdx, labelbreakh,
                        outputtablename, neib_spec),)
        print(mydf)
        return mydf

class EofScdplots():
    ''' Controls plotting of EofScd plots
        Needs raw_input files with following structure and header: 
            "Time Host Host_Scd Neib Neib_Scd Interaction DeltaScd AvgScd Etot Evdw Ecoul NChol Ntot"
            
        --> Bug1: binAvgScd seems not to be numeric!?
    '''
    def __init__(self, interaction, systemnames=Tranges.keys()):
        pairs = [('DPPC_DPPC', (-90, -50, 5)), ('DPPC_CHL1', (-50, -20, 5)), ('DUPC_CHL1', (-50, -20, 5)), ('CHL1_CHL1', (-30, -10, 5))]
        self.enthalpyranges = {}
        self.systemnames = systemnames
        self.Tlow = {}
        self.Thigh = {}
        for syst in systemnames:
            self.Tlow[syst], self.Thigh[syst] = Tranges[syst]
        self.interaction = interaction
        for pair in pairs:
            self.enthalpyranges[pair[0]] = pair[1]
    
    def delta_scd(self, pair, systemnames, interaction_pair, fileoutputname, neib_spec=None):
        ''' '''
        tables = {}
        tablelist = []
        for sysname in systemnames:
            tables[sysname] = self.temperature_avg(sysname, sysname, pair, interaction_pair, neib_spec=neib_spec)
            tablelist.append((sysname, sysname))
#'\n{0}fin$weight <- {0}fin$weight/sum({0}fin$weight)'
        final_table = merge_data('final_table', 'System', *tablelist)
        print(final_table)
        plot = ggplot2.ggplot(final_table)\
                + ggplot2.aes_string(x='AvgScd', y='DeltaScd',  color='System', weight='weight')\
                + ggplot2.geom_point(ggplot2.aes_string(shape='factor(NChol)'))\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.2, 1.0, 0.2], pair=pair)\
                + add_axis('y', 'deltascd', breaks=[0, 0.3, 0.1], pair=pair)\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' pair')\
                + ggplot2.guides(color=ggplot2.guide_legend("System"), shape=ggplot2.guide_legend("NChol"))\
                + ggplot2.theme_light() + my_theme()\
            #save_plot(filename, plot, width=25, height=20)
        gr.pdf(file=fileoutputname, width=10, height=7 )
        print(plot)
        return gr.dev_off()
    def parts_together(self, pair, sysname, filename, neib_spec=None):
        '''
        Plot all interactionpairs together
        '''
        if self.interaction == 'complete':
            return
        breaks_inter = {'head-tail':[-60, 10, 20],\
                        'head-tailhalfs':[-20, 0, 5],\
                        'carbons':[-2.5, 0, 0.1],\
                        }
        dt = self.temperature_avg('dataframe', sysname, pair, neib_spec=neib_spec, interaction_pair='all')
        if self.interaction == 'carbons' and neib_spec is None:
            dt = ro.r(\
                      'dataframe[,paste0("int",1:2) := tstrsplit(Interaction,"_")]'
                      '\ndataframe'
                      )
            print(dt)
            plot = ggplot2.ggplot(dt)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', weight='weight')\
                + ggplot2.geom_point()\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[0.2, 1.0, 0.4], limits=[-0.2, 1.0], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=[-2.5, 0, 1], pair=pair)\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.theme_light() + my_theme()\
                + ggplot2.facet_grid('int1 ~ int2')
            #save_plot(filename, plot, width=25, height=20)
            gr.pdf(file=filename,  width=10, height=7)
            print(plot)
            return gr.dev_off()
        elif self.interaction == 'carbons' and neib_spec is not None:
            dt = ro.r(\
                      'dataframe[,paste0("int",1:2) := tstrsplit(Interaction,"_")]'
                      '\ndataframe'
                      )
            print(dt)
            plot = ggplot2.ggplot(dt)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', color='factor(NChol)', weight='weight')\
                + ggplot2.geom_point(alpha=0.3)\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[0.2, 1.0, 0.4], limits=[-0.2, 1.0], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=[-2.5, 0, 1], pair=pair)\
                + ggplot2.guides(color=ggplot2.guide_legend("NChol"))\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.facet_grid('int1 ~ int2')\
                + ggplot2.theme_light() + my_theme()\
            #save_plot(filename, plot, width=25, height=20)
            gr.pdf(file=filename, width=10, height=7)
            print(plot)
            return gr.dev_off()
        elif self.interaction == 'head-tailhalfs' and neib_spec is not None:
            dt = ro.r(\
                      'dataframe <- dataframe[Interaction %in% c("t12_t12", "t22_t22")]'
                      '\ndataframe'
                      )
            print(dt)
            plot = ggplot2.ggplot(dt)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', color='factor(NChol)', weight='weight')\
                + ggplot2.geom_point(alpha=0.3)\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.2, 1.0, 0.4], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=breaks_inter[self.interaction], limits=[-25, 0], pair=pair)\
                + ggplot2.guides(color=ggplot2.guide_legend("NChol"))\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.facet_grid('Interaction ~ .')\
                + ggplot2.theme_light() + my_theme()\
            #save_plot(filename, plot, width=25, height=20)
            gr.pdf(file=filename, width=10, height=7)
            print(plot)
            return gr.dev_off()
        elif neib_spec is None:
            plot = ggplot2.ggplot(dt)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', color='Interaction', weight='weight')\
                + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.4, 1.0, 0.2], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=breaks_inter[self.interaction], pair=pair)\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.theme_light() + my_theme()
        else:
            plot = ggplot2.ggplot(dt)\
                    + ggplot2.aes_string(x='AvgScd', y='Etot', color='factor(NChol)', weight='weight')\
                    + ggplot2.geom_point(ggplot2.aes_string(size='weight'), alpha=0.6)\
                    + ggplot2.geom_smooth(ggplot2.aes_string(), size=1., se='False')\
                    + add_axis('x', 'avgscd', breaks=[-0.4, 1.0, 0.2], pair=pair)\
                    + add_axis('y', 'enthalpy', breaks=breaks_inter[self.interaction], pair=pair)\
                    + ggplot2.theme_light() + my_theme()\
                    + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                    + ggplot2.guides(color=ggplot2.guide_legend("NChol"))\
                    + ggplot2.facet_grid('Interaction ~ .')
        gr.pdf(file=filename)
        print(plot)
        gr.dev_off()
    def all_systems(self, pair, interaction_pair, filename, neib_spec=None):
        '''
        Plot all systems together 
        '''
        tables = {}
        tablelist = []
        for sysname in self.systemnames:
            tables[sysname] = self.temperature_avg(sysname, sysname, pair, interaction_pair, neib_spec=neib_spec)
            tablelist.append((sysname, sysname))
#'\n{0}fin$weight <- {0}fin$weight/sum({0}fin$weight)'
        final_table = merge_data('final_table', 'System', *tablelist)
        print(final_table)
        plot = ggplot2.ggplot(final_table)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', color='System', weight='weight')\
                + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.4, 1.0, 0.2], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=self.enthalpyranges[pair], pair=pair)\
                + ggplot2.scale_size("weight")\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.theme_light() + my_theme()
#                + ggplot2.geom_smooth(se='False')\
        gr.pdf(file=filename, width=10, height=7)
        print(plot)
        gr.dev_off()
    def energy_components(self, pair, systemname, interaction_pair, filename):
        '''
        Plot Vdw and Coulomb separately
        '''
        #=======================================================================
        # tables = {}
        # tablelist = []
        # for sysname in self.systemnames:
        #     tables[sysname] = self.temperature_avg(sysname, sysname, pair, interaction_pair)
        #     tablelist.append((sysname, sysname))
        # final_table = merge_data('final_table', 'System', *tablelist)
        #=======================================================================
        final_table = self.temperature_avg(systemname, systemname, pair, interaction_pair)
        plot = ggplot2.ggplot(final_table)\
                + ggplot2.aes_string(size='weight')\
                + ggplot2.geom_point(ggplot2.aes_string(x='AvgScd', y='Evdw'), color='red')\
                + ggplot2.geom_point(ggplot2.aes_string(x='AvgScd', y='Ecoul'), color='blue')\
                + ggplot2.geom_smooth(ggplot2.aes_string(x='AvgScd', y='Evdw'), color='red')\
                + ggplot2.geom_smooth(ggplot2.aes_string(x='AvgScd', y='Ecoul'),color='blue')\
                + add_axis('x', 'avgscd', breaks=[-0.4, 1.0, 0.2], pair=pair)\
                + ggplot2.ggtitle('-'.join(pair.split("_"))+' interaction')\
                + ggplot2.theme_light() + my_theme()
                #+ add_axis('y', 'enthalpy', breaks=[-50, 0, 5], pair=pair)\
        gr.pdf(file=filename)
        print(plot)
        gr.dev_off()

    def pairs_together(self, datasources, filename, interaction_pair='w_W', neib_spec=None): 
        tables = {}
        tablelist = []
        for sysname, pair in datasources:
            tables[sysname] = self.temperature_avg(pair, sysname, pair, interaction_pair, neib_spec=neib_spec)
            tablelist.append((pair, pair))
#'\n{0}fin$weight <- {0}fin$weight/sum({0}fin$weight)'
        final_table = merge_data('final_table', 'Pair', *tablelist)
        print(final_table)
        plot = ggplot2.ggplot(final_table)\
                + ggplot2.aes_string(x='AvgScd', y='Etot', color='Pair', weight='weight')\
                + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.4, 1.0, 0.2])\
                + add_axis('y', 'enthalpy', breaks=[-50, -10, 10])\
                + ggplot2.scale_size("weight")\
                + ggplot2.theme_light() + my_theme()
#                + ggplot2.geom_smooth(se='False')\
        gr.pdf(file=filename, width=10, height=7)
        print(plot)
        gr.dev_off()

    def standard_plot(self, systemname, pair, interaction_pair, filename, neib_spec=None):
        ''' Creates a standard EofScd plot of one system '''
        tavg = self.temperature_avg(systemname, systemname, pair, interaction_pair, neib_spec=neib_spec)
        print(tavg)
        titlepair = []
        for lip in pair.split('_'):
            if lip == 'CHL1':
                titlepair.append('CHOL')
            else:
                titlepair.append(lip)
        title = '-'.join(titlepair)
        if tavg is None:
            return
        if neib_spec is None:
            plot = ggplot2.ggplot(tavg)\
                + ggplot2.aes_string(x='AvgScd', y='Etot')\
                + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                + ggplot2.geom_smooth(se='False')\
                + add_axis('x', 'avgscd', breaks=[-0.2, 1.0, 0.2], pair=pair)\
                + add_axis('y', 'enthalpy', breaks=self.enthalpyranges[pair], pair=pair)\
                + ggplot2.ggtitle(title+' interaction')\
                + ggplot2.theme_light() + my_theme()
        elif neib_spec == 'ntot':
            print("PLOTTING NTOT")
            plot = ggplot2.ggplot(tavg)\
                    + ggplot2.aes_string(x='AvgScd', y='Etot', color='factor('+neib_spec+')', weight='weight')\
                    + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                    + ggplot2.geom_smooth(se='False')\
                    + add_axis('x', 'avgscd', breaks=[-0.2, 1.0, 0.2], pair=pair)\
                    + add_axis('y', 'enthalpy', breaks=self.enthalpyranges[pair], pair=pair)\
                    + ggplot2.guides(color=ggplot2.guide_legend(neib_spec))\
                    + ggplot2.ggtitle(title+' interaction')\
                    + ggplot2.theme_light() + my_theme()
        else:
            plot = ggplot2.ggplot(tavg)\
                    + ggplot2.aes_string(x='AvgScd', y='Etot', color='factor('+neib_spec+')', weight='weight')\
                    + ggplot2.geom_point(ggplot2.aes_string(size='weight'))\
                    + add_axis('x', 'avgscd', breaks=[-0.2, 1.0, 0.2], pair=pair)\
                    + add_axis('y', 'enthalpy', breaks=self.enthalpyranges[pair], pair=pair)\
                    + ggplot2.guides(color=ggplot2.guide_legend(neib_spec))\
                    + ggplot2.ggtitle(title+' interaction')\
                    + ggplot2.theme_light() + my_theme()
                    #+ ggplot2.geom_smooth(se='False')\
        gr.pdf(file=filename, width=10, height=7)
        print(plot)
        gr.dev_off()

    def bin_raw_data(self, outputtablename, datatablename, interaction_pair, column='AvgScd', breakl=-0.5, breakh=1.0, breakdx=0.05, neib_spec=None):
        ''' Discretize data by aggregating specified column '''
        print("Binning... {} : {}".format(datatablename, interaction_pair))
        labelbreakh = breakh-breakdx
        print("interaction pair is:", interaction_pair)
        if interaction_pair == 'all' and neib_spec is not None:
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\nbckp_data <- {0}[NChol<5]'
                '\n{6} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=list(bin{1}, Interaction, {7})][NChol<5]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Interaction, {7})][,N]'
                '\n{6}'\
                .format(datatablename, column,\
                        breakl, breakh, breakdx, labelbreakh,\
                        outputtablename, neib_spec)\
                )
        #=======================================================================
        # elif interaction_pair == 'all' and neib_spec is None:
        #     mydf = ro.r(\
        #         '\n{0}$bin{1} <- cut({0}${1},'
        #                         'breaks=seq({2}, {3}, {4}),'
        #                         'labels=seq({2}, {5}, {4}))'
        #         '\nbckp_data <- {0}[NChol<5]'
        #         '\n{6} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=list(bin{1}, Interaction, {7})][NChol<5]'
        #         '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Interaction, NChol)][,N]'
        #         '\n{6}'\
        #         .format(datatablename, column,\
        #                 breakl, breakh, breakdx, labelbreakh,\
        #                 outputtablename)\
        #         )
        #=======================================================================
        elif interaction_pair == 'all' and neib_spec is None:
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\nbckp_data <- {0}'
                '\n{6} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=list(bin{1}, Interaction)]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Interaction)][,N]'
                '\n{6}'\
                .format(datatablename, column,\
                        breakl, breakh, breakdx, labelbreakh,\
                        outputtablename)\
                )
        elif interaction_pair != 'all' and neib_spec == 'ntot':
            print("NTOT")
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\n{0}$binNtot <- cut({0}$NewNtot,'
                                'breaks=seq(0, 15, 3),'
                                'labels=seq(0, 12, 3))'
                '\nbckp_data <- na.omit({0})'
                '\n{0} <- na.omit({0})'
                '\n{6} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=list(bin{1}, Interaction, binNtot)]'
                '\n{6}$weight <- bckp_data[,.N,by=list(bin{1}, Interaction, binNtot)][,N]'
                '\n{6}'\
                .format(datatablename, column,\
                        breakl, breakh, breakdx, labelbreakh,\
                        outputtablename)\
                )
        elif interaction_pair != 'all' and neib_spec is not None:
            mydf = ro.r(\
                '\n{0}$bin{1} <- cut({0}${1},'
                                'breaks=seq({2}, {3}, {4}),'
                                'labels=seq({2}, {5}, {4}))'
                '\n{0} <- {0}[Interaction=="{6}"][,Interaction:=NULL][NChol<5]'
                '\nbckp_data <- {0}'
                '\n{7} <- {0}[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=list(bin{1}, NewNChol)]'
                '\n{7}$weight <- bckp_data[,.N,by=list(bin{1}, NewNChol)][,N]'
                '\n{7}'\
                .format(datatablename, column,\
                        breakl, breakh, breakdx, labelbreakh,\
                        interaction_pair, outputtablename)\
                )
            print("Max CHOL neighbors:", ro.r('max({}$NChol)'.format(outputtablename)))
        elif interaction_pair != 'all' and neib_spec is None:
            mydf = ro.r(\
                        '\n{0}$bin{1} <- cut({0}${1},'
                                        'breaks=seq({2}, {3}, {4}),'
                                        'labels=seq({2}, {5}, {4}))'
                        '\n{0}intermed1 <- {0}[Interaction=="{6}"][,Interaction:=NULL]'
#                        '\n{0}intermed1 <- {0}[Interaction=="{6}"][,Interaction:=NULL]'
    #                    \n'{0}intermed2 <- {0}[,temperature:=NULL]\n'
    #                    \n'{0}intermed2'\
#                        '\n{0}fin <- {0}intermed1[,lapply(.SD, mean), by=bin{1}]'
                        '\n{7} <- {0}intermed1[,lapply(.SD, function(x) if (!is.numeric(x)) x else mean(x)), by=bin{1}]'
                        '\n{7}$weight <- {0}intermed1[,.N,by=bin{1}][,N]'
                        '\n{7}'\
                        .format(datatablename, column, breakl, breakh, breakdx,\
                                labelbreakh, interaction_pair, outputtablename, )\
                        )
        #print("Thats my df:", mydf)
        print("Finished binning")
        return mydf


    
    def temperature_avg(self, outputtable, systemname, pair, interaction_pair, neib_spec=None):
        ''' ___ Calculate average over temperature range ___
        Variables are:
            mysys: Systemname (like dppc_chol)
            Tlow['sys'], Thigh['sys']: Temperature range
            pair: lipidtype pair (DPPC_DPPC)
            interaction: part of interaction (complete/headtail/headtailhalfs/...)
            interaction_pair: (w_w/h_t/...)
            nchol: None | not None
        Final data.frame structure:
            "binAvgScd Time Host Host_Scd Neib Neib_Scd DeltaScd AvgScd Etot Evdw Ecoul NChol weight"
        '''
        print("INPUT:", outputtable, systemname, pair, interaction_pair,)
        framenames = []
        for temp in range(self.Tlow[systemname], self.Thigh[systemname]+1, 10):
            print("At temperature:", temp)
            system = '{}_{}'.format(systemname, temp)
            print(system)
            if self.interaction == 'complete':
                file_to_read = '{}/Eofscd{}.dat'.format(system, pair)
            else:
                file_to_read = '{}/Eofscd{}{}.dat'.format(system, pair, self.interaction)
            if os.path.exists(file_to_read):
                read_datafile(system, file_to_read)
            else:
                print("File {} does not exist".format(file_to_read))
                return None
        #Averaging before everything's collected=============
            df = self.bin_raw_data(system, system, interaction_pair, neib_spec=neib_spec)
            print("binned df:", df)
            framenames.append(system)
        framenames = [(i, i[-3:]) for i in framenames]
        print("Framenames:", framenames)
        dt = merge_data(outputtable, 'temperature', *framenames)
        print("MERGED DATA:", dt)
        if neib_spec == 'ntot':
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))'
                            '\n{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binAvgScd, Interaction, binNtot)]'
                            '\ninsignificant <- 0.01*max({0}$weight)'
                            '\n{0} <- {0}[weight>insignificant]'
                            '\n{0}'
                                #'{0} <- {0}[,Lipid_type:=NULL][weight>insignificant]\n'
                         #'\n{1}$NChol <- factor({1}$NChol)'
                         .format(outputtable))
            print("FINAL:", df_final)
        elif neib_spec is not None and interaction_pair == 'all':
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))'
                            '\n{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binAvgScd, Interaction, {1})]'
                            '\ninsignificant <- 0.01*max({0}$weight)'
                            '\n{0} <- {0}[weight>insignificant]'
                            '\n{0}'
                         #'\n{1}$NChol <- factor({1}$NChol)'
                         .format(outputtable, neib_spec))
        elif neib_spec is not None:
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))'
                            '\n{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binAvgScd, {1})]'
                            '\ninsignificant <- 0.01*max({0}$weight)'
                            '\n{0} <- {0}[weight>insignificant]'
                         #'\n{1}$NChol <- factor({1}$NChol)'
                         .format(outputtable, neib_spec))
        elif interaction_pair is 'all':
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))'
                            '\n{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=list(binAvgScd, Interaction)]'
                            '\ninsignificant <- 0.01*max({0}$weight)'
                            '\n{0} <- {0}[weight>insignificant]'
                         #'\n{1}$NChol <- factor({1}$NChol)'
                         .format(outputtable))
        elif neib_spec is None and interaction_pair != 'all':
            df_final = ro.r('{0} <- subset({0},select=-c(temperature))\n'
                            '{0} <- {0}[,lapply(.SD,weighted.mean,w=weight),by=binAvgScd]'\
                            '\ninsignificant <- 0.01*max({0}$weight)'
                            '\n{0} <- {0}[weight>insignificant]'
                         .format(outputtable))
        #print("FINALFRAME:", df_final)
        return df_final
        #======================================================================
        #     framenames.append(system)
        # print(framenames)
        # framenames = [(i, i[:-3]) for i in framenames]
        # print(framenames)
        # finalframe = system+'final'
        # dmerge = self.merge_data(finalframe, 'temperature', *framenames)
        # print(dmerge)
        # df_final = self.bin_raw_data(finalframe, interaction_pair)
        # return df_final
        #======================================================================

def read_datafile(dataname, datafile):
    df = ro.r('{} <- fread("{}")'.format(dataname, datafile))
    return df   # SysSource type AvgScd Etot Occurrence/weight NChol


def add_axis(dim, name, breaks, limits=None, pair=None):
    ''' Axes scales and labels
    dim: x/y/z axis
    breaks: (start, end, bin)
    limits: (start, end)
    '''
    if name == 'avgscd':
        name = ro.r('expression(bar("S"[CD]))')
    elif name == 'scd':
        name = ro.r('expression("S"[CD])')
    elif name == 'enthalpy':
        #name = ro.r('expression(paste("H"[{}],"(S"[CD],") / kJ/mol"))'.format(pair))
        name = ro.r('expression(paste("H","(S"[CD],") / kJ/mol"))')
    elif name == 'deltascd':
        name = ro.r('expression(paste(Delta,"S"[CD]))')
    elif name == 'neighbors':
        name = ro.r('expression(paste("N","(S"[CD],")"))')
    
    if breaks == 'auto':
        raise NotImplementedError("not implemented")
        breaks = 'NULL'
        limits = 'NULL'
    else:
        if limits is None:
            limits = ro.FloatVector([breaks[0], breaks[1]])
        else:
            limits = ro.FloatVector(limits)
        breaks = ro.FloatVector(np.around(np.arange(breaks[0], breaks[1]+1, breaks[2]), decimals=1))
    expand = ro.FloatVector([0,0])
    if dim == 'x':
        axis = ggplot2.scale_x_continuous(name, limits=limits, breaks=breaks, expand=expand)
    if dim == 'y':
        axis = ggplot2.scale_y_continuous(name, limits=limits, breaks=breaks, expand=expand)
    return axis


def my_theme():
    ''' pass theme here '''
    theme = ggplot2.theme(**{\
                'axis.text':        ggplot2.ggplot2.element_text(size=14, colour="black"),\
                'axis.title':       ggplot2.ggplot2.element_text(size=20),\
                'axis.ticks':       ggplot2.ggplot2.element_line(size=.5),\
                'panel.background': ggplot2.ggplot2.element_rect(fill="white"),\
                'panel.border':     ggplot2.ggplot2.element_rect(colour="black", size=0.5),\
                'panel.grid.major': ggplot2.ggplot2.element_line(colour="grey90", size=0.5),\
                'panel.grid.minor': ggplot2.ggplot2.element_line(colour="grey90", size=0.5),\
                'legend.title':     ggplot2.ggplot2.element_text(size=20),\
                'legend.text':      ggplot2.ggplot2.element_text(size =14),\
                'legend.key':       ggplot2.ggplot2.element_blank(),\
                'plot.title':       ggplot2.ggplot2.element_text(size=20, hjust = 0.5),\
                'legend.key.width': ro.r.unit(1,"lines"),\
                'legend.key.height':ro.r.unit(1.5,"lines")\
                })
    return theme

def save_plot(filename, plot, path='.', device='pdf', width=15, height=20, unit='cm', dpi=360):
    ''' Save plot commands '''
    ro.r('ggsave("{}", plot = {}, device = "{}", path = "{}",'\
         'scale = 1, width = {}, height = {}, units = "{}",'\
         'dpi = {}, )'.format(filename, plot, device, path, width, height, unit, dpi))

def merge_data(tablename, groupname, *args):
    ''' merges data.tables
        args must be tuple: (data.table-name, frame-specifier)
        Something like: groupname = Temperature, arg=(df1, DPPC_CHOL) ...
     '''
    print('Merging data . . .')
    for arg in args:
        #print(arg)
        #print("Mergedata:", ro.r(arg[0]))
        ro.r('{0}${1}="{2}"'.format(arg[0], groupname, arg[1]))
    all_frames = ','.join([arg[0] for arg in args])
    #print("All frames:", all_frames)
    df = ro.r('{} <- rbind({})'.format(tablename, all_frames))
    return df

